### ISSUE TITLE
proc/readproc.h: File o directory non esistente

### ISSUE THREAD

**Issue by ancestral95** [scaidermern/top-processes#1]
Hi,
I'm trying to use your tool, but when i launch `make` or `make all` it say 
> cc -Wall -Wextra   -c -o top_proc.o top_proc.c
top_proc.c:3:27: fatal error: proc/readproc.h: File o directory non esistente
compilation terminated.
<incorporato>: set di istruzioni per l'obiettivo "top_proc.o" non riuscito
make: *** [top_proc.o] Errore 1

**Comment by scaidermern** [comment]
You need to install libprocps headers. Depending on your system they are located in a package called `libprocps-dev` or `procps-ng-devel` or something similar.
